<a href="https://colab.research.google.com/github/MaCroDmT/ARTIFICIAL-INTELLIGENCE-AND-EXPERT-SYSTEM/blob/main/I_21_45640_3_Week_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Generate an intial state of NPuzzle

In [ ]:
import numpy as np
import random
import math

In [ ]:
def get_state():
    N = random.choice([3,4,5]) #eta default value
    state = [item for item in range(N*N)]# [0,1,2,...,15]
    random.shuffle(state)
    tmp = np.array(state)
    print(tmp.reshape(N,N))
    return state

In [ ]:
def get_dim(s):
  return int(math.sqrt(len(s)))

In [ ]:
s = get_state()
print(s)
print('Dimension:', get_dim(s))

[[3 7 1]
 [5 0 8]
 [2 6 4]]
[3, 7, 1, 5, 0, 8, 2, 6, 4]
Dimension: 3


# Calculate inversion

Inversion is a pair of tiles that are in the reverse order from where they ought to be. In our case, the bigger number is in front of the smaller one.



![Capture.JPG](attachment:Capture.JPG)

In [ ]:
def get_invCount(s):
    count = 0
    for i in range(len(s)):
        for j in range(i+1,len(s)):
            if s[j]!=0 and s[i] > s[j]: count += 1 #eta buje korte hobe sir will ask question
    return count

In [ ]:
s = get_state()
print(s)
print(get_invCount(s))

[[15 10 16  8 14]
 [ 9  3 11 20 24]
 [ 6 12 18  5  7]
 [ 1 13 21 22  2]
 [23 17 19  0  4]]
[15, 10, 16, 8, 14, 9, 3, 11, 20, 24, 6, 12, 18, 5, 7, 1, 13, 21, 22, 2, 23, 17, 19, 0, 4]
131


In [ ]:
s.index(0)

23

# **Find blank row**

In [ ]:
# find row position of the blank tile
def get_blank_row(s):
    index = s.index(0)
    return index

puzzle_state = [6, 5, 1, 4, 7, 3, 0, 8, 2]
blank_row_index = get_blank_row(puzzle_state)
if blank_row_index is not None:
    print(f"Blank tile is in row {blank_row_index}")
else:
    print("Blank tile not found in the puzzle state.")






Blank tile is in row 6


# Solvability Rules

In [ ]:
# apply the rules to decide solvability
#  N, I, R
# define a method to return solvability (input S)
# return True if solvable or False if not
def isSolvable(state):
    N = get_dim(state)
    I = get_invCount(state)
    R = get_blank_row(state)

    if N % 2 == 1:
        return I % 2 == 0
    else:
        if R % 2 == 0:
            return I % 2 == 1
        else:
            return I % 2 == 0

puzzle_state = [6, 5, 1, 4, 7, 3, 0, 8, 2]
print(isSolvable(puzzle_state))





False


In [ ]:
s = get_state()
isSolvable(s)


[[8 2 0]
 [6 5 4]
 [7 3 1]]


True

In [ ]:
s = get_state()
while(isSolvable(s)==False):
  s = get_state()
print(s)


[[ 2  3  8  5]
 [11 13 10  9]
 [14 12  0  7]
 [ 4 15  6  1]]
[2, 3, 8, 5, 11, 13, 10, 9, 14, 12, 0, 7, 4, 15, 6, 1]
